name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch. You can change this to any branch you want.
  workflow_dispatch:  # Allows manual triggering
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
    
    - name: Build the Jars
      run: | 
        sudo apt update
        sudo apt install maven -y
        cd ./userservice1
        mvn clean install -D skipTests
        cd ../
        cd ./userservice2
        mvn clean install -D skipTests
        cd ../
        cd ./orderservice
        mvn clean install -D skipTests
        cd ../
        cd ./apigateway
        mvn clean install -D skipTests
        cd ../

    # Deploy to VM via SSH
    - name: Deploy to VM
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_PRIVATE_KEY }} 
      run: |
        echo "$SSH_PRIVATE_KEY" > azure_key.pem
        chmod 400 azure_key.pem

        ssh -o StrictHostKeyChecking=no -i azure_key.pem azureuser@${{ secrets.AZURE_IP_ADDRESS }} << 'EOF'
          sudo docker-compose down
          sudo rm -rf /home/azureuser/app
          sudo mkdir -p /home/azureuser/app
          sudo chown azureuser:azureuser /home/azureuser/app
          sudo chmod u+w /home/azureuser/app
        EOF

        scp -o StrictHostKeyChecking=no -i azure_key.pem -r ./* azureuser@${{ secrets.AZURE_IP_ADDRESS }}:~/.
        
        # Use SSH to execute commands on your EC2 instance
        ssh -o StrictHostKeyChecking=no -i azure_key.pem azureuser@${{ secrets.AZURE_IP_ADDRESS }} << 'EOF'
          echo "Deploying application to EC2..."
          rm -rf /home/azureuser/app/azure_key.pem
          cd /home/azureuser/app || exit 1  # Go to your app directory
          sudo docker-compose up -d
          echo "Deployment complete!"
        EOF
        
        rm azure_key.pem  # Clean up the temporary file
